# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\mrfz\token.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Token(object):
    def setupUi(self, Token):
        Token.setObjectName("Token")
        Token.resize(610, 335)
        self.verticalLayout = QtWidgets.QVBoxLayout(Token)
        self.verticalLayout.setContentsMargins(20, 50, 20, 50)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        self.CardWidget_2 = CardWidget(Token)
        self.CardWidget_2.setObjectName("CardWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.CardWidget_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.BodyLabel_2 = BodyLabel(self.CardWidget_2)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.horizontalLayout.addWidget(self.BodyLabel_2)
        self.LineEdit_2 = LineEdit(self.CardWidget_2)
        self.LineEdit_2.setReadOnly(True)
        self.LineEdit_2.setObjectName("LineEdit_2")
        self.horizontalLayout.addWidget(self.LineEdit_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BodyLabel_3 = BodyLabel(self.CardWidget_2)
        self.BodyLabel_3.setObjectName("BodyLabel_3")
        self.horizontalLayout_2.addWidget(self.BodyLabel_3)
        self.LineEdit_3 = LineEdit(self.CardWidget_2)
        self.LineEdit_3.setReadOnly(True)
        self.LineEdit_3.setObjectName("LineEdit_3")
        self.horizontalLayout_2.addWidget(self.LineEdit_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.CardWidget_2)
        self.CardWidget = CardWidget(Token)
        self.CardWidget.setObjectName("CardWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.CardWidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.BodyLabel_4 = BodyLabel(self.CardWidget)
        self.BodyLabel_4.setObjectName("BodyLabel_4")
        self.horizontalLayout_5.addWidget(self.BodyLabel_4)
        self.LineEdit_4 = LineEdit(self.CardWidget)
        self.LineEdit_4.setObjectName("LineEdit_4")
        self.horizontalLayout_5.addWidget(self.LineEdit_4)
        self.horizontalLayout_5.setStretch(0, 1)
        self.horizontalLayout_5.setStretch(1, 9)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.BodyLabel = BodyLabel(self.CardWidget)
        self.BodyLabel.setObjectName("BodyLabel")
        self.horizontalLayout_4.addWidget(self.BodyLabel)
        self.LineEdit = LineEdit(self.CardWidget)
        self.LineEdit.setInputMask("")
        self.LineEdit.setText("")
        self.LineEdit.setObjectName("LineEdit")
        self.horizontalLayout_4.addWidget(self.LineEdit)
        self.PushButton = PushButton(self.CardWidget)
        self.PushButton.setObjectName("PushButton")
        self.horizontalLayout_4.addWidget(self.PushButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.CardWidget)
        self.verticalLayout.setStretch(0, 8)
        self.verticalLayout.setStretch(1, 4)

        self.retranslateUi(Token)
        QtCore.QMetaObject.connectSlotsByName(Token)

    def retranslateUi(self, Token):
        _translate = QtCore.QCoreApplication.translate
        Token.setWindowTitle(_translate("Token", "Form"))
        self.BodyLabel_2.setText(_translate("Token", "请登录鹰角网络官方网站，网址为："))
        self.LineEdit_2.setText(_translate("Token", "https://ak.hypergryph.com/user/login"))
        self.BodyLabel_3.setText(_translate("Token", "请获取登录凭证，网址为："))
        self.LineEdit_3.setText(_translate("Token", "https://web-api.hypergryph.com/account/info/hg"))
        self.BodyLabel_4.setText(_translate("Token", "请输入用户名："))
        self.LineEdit_4.setPlaceholderText(_translate("Token", "用于区分不同账号，默认为default"))
        self.BodyLabel.setText(_translate("Token", "请输入登录凭证："))
        self.LineEdit.setPlaceholderText(_translate("Token", "请输入登录凭证"))
        self.PushButton.setText(_translate("Token", "确认提交"))
from qfluentwidgets import BodyLabel, CardWidget, LineEdit, PushButton
